### ISSUE TITLE
Uninitialized condition variables in Barnes

### ISSUE THREAD

**Issue by kubanrob** [SakalisC/Splash-3#11]
I was tring to run Barnes-Hut on MacOS and noticed some deadlocks in `hackcofm`.

It seems like the condition variable in most cells are never initialized properly (only the root one?). This leads to waiters for `Done(cell)` never releasing the mutex, as the call to `pthread_cond_wait` fails. Consequently, the thread trying to signal that waiter gets blocked too.

The Linux distribution I tried run it on does not seem to mind the uninitialized CVs.

I assume this can be fixed by either properly initializing the CVs or using an array similar to the locks. Initializing the CV in `makecell/makeleaf` makes it run for me, but calling `pthread_cond_init` that often might not be not an ideal solution.

I don't know if this is a relevant issue for you, but it's probably not a bad thing to let you now.

Best regards,
Robert

**Comment by SakalisC** [comment]
Thank you for reporting this. I will take a look and see what makes sense to do. I am not sure if switching to an array would be that much better.
