### ISSUE TITLE
Do you know how to replace some c11 stuff, such as atomic_thread_fence with older alternative one?

### ISSUE THREAD

**Issue by JianpingZeng** [SakalisC/Splash-3#8]
Hi,
Sorry for bothering you guys. I have to build the Splash 3 with an older version of dragonegg 4.6 + llvm 3.0, which don't support the c11 standard, and I can't migrate our older llvm compiler to the latest one. So do you have any solutions to replace c11 stuff, such as atomic_thread_fence with older alternative one?

BTW, the reason why I don't use splash 2 is our research needs to bypass data race.

Best,
Jianping.

**Comment by SakalisC** [comment]
Hi Jianping,

I am not sure which of these ways will work with such an old version of LLVM, but here's some alternatives:

1.
GCC has a [`__sync_synchronize`](https://gcc.gnu.org/onlinedocs/gcc-4.6.2/gcc/Atomic-Builtins.html) intrinsic that works as a memory fence. I would suggest trying and seeing if it works with dragonegg and LLVM.

2.
There is also an SSE intrinsic for a memory fence, `__builtin_ia32_mfence`. This is x86 specific of course.

3.
Finally, again for x86, there is always the possibility of adding a memory fence manually, using the `mfence` x86 instruction, using something like `asm volatile ("mfence")`. I haven't tested the ASM code, so you might need to look into it a bit more.

I hope these are helpful.

Best regards,

Christos

**Comment by JianpingZeng** [comment]
Thanks for your kindly help! I will try to use your first suggestion because we use the arm target machine. So the other two solutions are not applied to our research.

Best,
Jianping.
